/**
 * D&D Terms Module for Narrator Master
 * Pre-populated list of common D&D 5e terms for transcription accuracy
 * @module dnd-terms
 */

/**
 * Default D&D 5e terms organized by category
 * Used to improve transcription accuracy for fantasy terminology
 * @constant {Array<string>}
 */
export const DEFAULT_DND_TERMS = [
    // Common D&D 5e Classes
    'Barbarian',
    'Bard',
    'Cleric',
    'Druid',
    'Fighter',
    'Monk',
    'Paladin',
    'Ranger',
    'Rogue',
    'Sorcerer',
    'Warlock',
    'Wizard',
    'Artificer',

    // Common D&D 5e Races
    'Dwarf',
    'Elf',
    'Halfling',
    'Human',
    'Dragonborn',
    'Gnome',
    'Half-Elf',
    'Half-Orc',
    'Tiefling',
    'Aarakocra',
    'Aasimar',
    'Genasi',
    'Goliath',
    'Kenku',
    'Tabaxi',
    'Triton',
    'Firbolg',
    'Kobold',
    'Yuan-ti',

    // Common Spells (Level 0-2)
    'Fireball',
    'Magic Missile',
    'Eldritch Blast',
    'Healing Word',
    'Cure Wounds',
    'Mage Armor',
    'Shield',
    'Counterspell',
    'Dispel Magic',
    'Detect Magic',
    'Identify',
    'Prestidigitation',
    'Thaumaturgy',
    'Druidcraft',
    'Mending',
    'Light',
    'Sacred Flame',
    'Vicious Mockery',
    'Toll the Dead',
    'Guidance',
    'Spare the Dying',
    'True Strike',
    'Thunderwave',
    'Burning Hands',
    'Chromatic Orb',
    'Guiding Bolt',
    'Inflict Wounds',
    'Bless',
    'Bane',
    'Command',
    'Sleep',
    'Charm Person',
    'Disguise Self',
    'Silent Image',
    'Invisibility',
    'Misty Step',
    'Shatter',
    'Scorching Ray',
    'Flaming Sphere',
    'Moonbeam',
    'Spiritual Weapon',
    'Aid',
    'Lesser Restoration',
    'Hold Person',
    'Suggestion',
    'Detect Thoughts',

    // Common Higher Level Spells
    'Lightning Bolt',
    'Haste',
    'Fly',
    'Revivify',
    'Mass Healing Word',
    'Polymorph',
    'Greater Invisibility',
    'Banishment',
    'Wall of Fire',
    'Ice Storm',
    'Cone of Cold',
    'Raise Dead',
    'Greater Restoration',
    'Scrying',
    'Teleportation Circle',
    'Dominate Person',
    'Hold Monster',
    'Resurrection',
    'True Resurrection',
    'Wish',
    'Power Word Kill',
    'Meteor Swarm',
    'Time Stop',

    // Common Game Terms
    'initiative',
    'advantage',
    'disadvantage',
    'proficiency',
    'saving throw',
    'ability check',
    'skill check',
    'perception check',
    'stealth check',
    'insight check',
    'investigation check',
    'arcana check',
    'history check',
    'nature check',
    'religion check',
    'animal handling',
    'athletics',
    'acrobatics',
    'sleight of hand',
    'performance',
    'persuasion',
    'deception',
    'intimidation',
    'survival',
    'medicine',
    'concentration',
    'bonus action',
    'reaction',
    'opportunity attack',
    'critical hit',
    'natural twenty',
    'nat twenty',
    'natural one',
    'armor class',
    'hit points',
    'spell slot',
    'spell attack',
    'melee attack',
    'ranged attack',
    'weapon attack',
    'short rest',
    'long rest',
    'death saving throw',

    // Common Creatures
    'Goblin',
    'Orc',
    'Troll',
    'Dragon',
    'Kobold',
    'Bugbear',
    'Hobgoblin',
    'Gnoll',
    'Owlbear',
    'Beholder',
    'Mind Flayer',
    'Illithid',
    'Lich',
    'Vampire',
    'Werewolf',
    'Zombie',
    'Skeleton',
    'Wraith',
    'Specter',
    'Gelatinous Cube',
    'Mimic',
    'Rust Monster',
    'Displacer Beast',
    'Tarrasque',
    'Balor',
    'Pit Fiend',
    'Ancient Dragon',
    'Young Dragon',
    'Wyrmling',

    // Common Items and Equipment
    'longsword',
    'shortsword',
    'greatsword',
    'battleaxe',
    'warhammer',
    'mace',
    'quarterstaff',
    'dagger',
    'rapier',
    'scimitar',
    'longbow',
    'shortbow',
    'crossbow',
    'heavy crossbow',
    'light crossbow',
    'hand crossbow',
    'leather armor',
    'studded leather',
    'chain mail',
    'plate armor',
    'scale mail',
    'half plate',
    'breastplate',
    'shield',
    'potion of healing',
    'greater healing',
    'superior healing',
    'supreme healing',
    'spell scroll',
    'magic item',
    'common magic item',
    'uncommon magic item',
    'rare magic item',
    'very rare magic item',
    'legendary magic item',
    'artifact',

    // Common Planes and Locations
    'Forgotten Realms',
    'Faerun',
    'Waterdeep',
    'Baldurs Gate',
    'Neverwinter',
    'Sword Coast',
    'Underdark',
    'Feywild',
    'Shadowfell',
    'Nine Hells',
    'Abyss',
    'Astral Plane',
    'Ethereal Plane',
    'Material Plane',
    'Elemental Plane',

    // Common Gods and Deities
    'Tiamat',
    'Bahamut',
    'Lolth',
    'Corellon',
    'Moradin',
    'Pelor',
    'Kelemvor',
    'Mystra',
    'Bane',
    'Bhaal',
    'Myrkul',
    'Asmodeus',
    'Orcus',
    'Demogorgon',

    // Common Conditions
    'blinded',
    'charmed',
    'deafened',
    'frightened',
    'grappled',
    'incapacitated',
    'invisible',
    'paralyzed',
    'petrified',
    'poisoned',
    'prone',
    'restrained',
    'stunned',
    'unconscious',
    'exhaustion'
];
